# frozen_string_literal: true

#
# Model the Schema.org `Service`. See https://schema.org/Service
#
module SchemaOrg
  #
  # Model the Schema.org `Service`. See https://schema.org/Service
  # A service provided by an organization, e.g. delivery service, print services, etc.
  #
  # === Attributes
  #
  # - name: (String) - The name of the service.
  # - description?: (String) - Optional. A description of the service.
  # - url: (WebUrl) - URL of the service.
  # - provider?: (Organization) - Optional. The organization that provides this service.
  # - serviceType?: (String) - Optional. The type of service being offered, e.g. "food delivery", "transportation".
  # - areaServed?: (String or PostalAddress) - Optional. The geographic area where a service is provided.
  # - availableChannel?: (String) - Optional. A means to access the service (e.g. website, phone, in-person).
  # - termsOfService?: (String or WebUrl) - Optional. Human-readable terms of service documentation.
  # - category?: (String) - Optional. A category for the service.
  # - offers?: (Offer) - Optional. An offer or offers for the service.
  # - hoursAvailable?: (String) - Optional. The hours during which this service is available.
  # - sameAs?: (String) - Optional. URL of a reference Web page that unambiguously indicates the item's identity.
  # - serviceOutput?: (Types::Any) - Optional. The tangible thing generated by the service, e.g. a passport, permit, etc.
  # - audience?: (Types::Any) - Optional. An intended audience, i.e. a group for whom something was created.
  # - aggregateRating?: (Types::Any) - Optional. The overall rating, based on a collection of reviews or ratings.
  # - review?: (Types::Array) - Optional. A review of the service.
  # - providerMobility?: (Types::String) - Optional. Indicates the mobility of a provided service (e.g. 'static', 'dynamic').
  # - serviceArea?: (Types::Any) - Optional. The geographic area where the service is provided.
  # - alternateName?: (Types::String) - Optional. An alias for the service.
  # - availableLanguage?: (Types::Any) - Optional. A language someone may use with or at the service.
  # - contactPoint?: (Types::Any) - Optional. A contact point for the service.
  # - logo?: (Types::Any) - Optional. An associated logo for the service.
  # - mainEntityOfPage?: (Types::Any) - Optional. Indicates a page for which this service is the main entity being described.
  # - potentialAction?: (Types::Any) - Optional. Indicates a potential Action that can be performed on this service.
  # - hasCertification?: (Types::Any) - Optional. Certification information about the service.
  # - isRelatedTo?: (Types::Any) - Optional. A pointer to another, somehow related service.
  # - serviceLocation?: (Types::Any) - Optional. The location where the service is provided.
  # - identifier?: (Types::String) - Optional. The identifier property represents any kind of identifier for the service.
  # - image?: (Types::Any) - Optional. An image of the service.
  # - brand?: (Types::Any) - Optional. The brand associated with the service.
  # - slogan?: (Types::String) - Optional. A slogan or motto associated with the service.
  #
  class Service < Thing
    # Наследуем от Thing атрибуты: name, description?, url
    attribute :provider?, Organization
    attribute :serviceType?, Types::String
    attribute :areaServed?, Types::String
    attribute :availableChannel?, Types::String
    attribute :termsOfService?, Types::String
    attribute :category?, Types::String
    attribute :offers?, Types::Any
    attribute :hoursAvailable?, Types::String
    attribute :sameAs?, Types::String
    attribute :serviceOutput?, Types::Any
    attribute :audience?, Types::Any
    attribute :aggregateRating?, Types::Any
    attribute :review?, Types::Array
    attribute :providerMobility?, Types::String
    attribute :serviceArea?, Types::Any
    attribute :alternateName?, Types::String
    attribute :availableLanguage?, Types::Any
    attribute :contactPoint?, Types::Any
    attribute :logo?, Types::Any
    attribute :mainEntityOfPage?, Types::Any
    attribute :potentialAction?, Types::Any
    attribute :hasCertification?, Types::Any
    attribute :isRelatedTo?, Types::Any
    attribute :serviceLocation?, Types::Any
    attribute :identifier?, Types::String
    attribute :image?, Types::Any
    attribute :brand?, Types::Any
    attribute :slogan?, Types::String
  end
end
